### ISSUE TITLE
Please create a new release 'v1.0.2'

### ISSUE THREAD

**Issue by jiro4989** [ScottBrenner/generate-changelog-action#14]
Current latest version (`v1.0.1`) does not contains 'with: package-dir' options. I want to use this options.
https://github.com/ScottBrenner/generate-changelog-action/compare/1.0.1...master

But I don't want to use `@master` version.
Please create a new release.

**Comment by ScottBrenner** [comment]
https://github.com/ScottBrenner/generate-changelog-action/releases/tag/1.0.2 👍🏻

**Comment by jiro4989** [comment]
Thank you !!
