### ISSUE TITLE
Generated changelog empty

### ISSUE THREAD

**Issue by jnorkus** [ScottBrenner/generate-changelog-action#16]
I can't get it to work with the provided example and I think I know why.

From [lob/generate-changelog](https://github.com/lob/generate-changelog#generate-changelog) documentation:

_This is meant to be used so that for every patch, minor, or major version, you update the changelog prior to running npm version so that the git tag contains the commit that updated both the changelog and version._

If the action is triggered by a tag push it is already too late to generate the changelog.

**Comment by ScottBrenner** [comment]
Whoops, please open a pull request with a fix!

**Comment by jnorkus** [comment]
In the end I solved it by implementing the recommended flow, i.e. generating the changelog client side. This means I'm no longer using the action.
