### ISSUE TITLE
Change log include only last commit

### ISSUE THREAD

**Issue by cawa-93** [ScottBrenner/generate-changelog-action#17]
In my [workflow](https://github.com/cawa-93/vite-electron-builder/blob/228a12840fbbae1a915fa8d28c025c0d8b962d8c/.github/workflows/CICD.yml#L74-L93), the change log always includes only the last commit.

Reproduce:
- Create repo from template: [cawa-93/vite-electron-builder](https://github.com/cawa-93/vite-electron-builder)
- Make a few commits
- Push commit to main branch
- Wait for the `draft_release` job complete. It will create a draft of a new release. Only the last commit is included in this draft body.

At first I thought it was due to the lack of previous releases or git tags. But this is not the case.

You can check **[this](https://github.com/cawa-93/generate-changelog-action-issue)** demo repository.

- I made several commits.
- Pushed them into the repository.
- Published a release (this also created a git tag).
- Made a few more commits.
- Pushed them into the repository.
- Published new release.

Each time the list of changes contained only the last commit.

**Comment by ScottBrenner** [comment]
This reminds me of https://github.com/ScottBrenner/generate-changelog-action/issues/6#issuecomment-699524687 - could you try setting `fetch-depth: 0` to the checkout step in your workflow? reference: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches

**Comment by cawa-93** [comment]
Yes, it helped. Thanks.
