### ISSUE TITLE
Action cannot clone repo if a folder already exists with its name

### ISSUE THREAD

**Issue by michael-robbins** [ScottBrenner/generate-changelog-action#19]
I have a repo where there's a top level folder which is also the repo's name.
So running this action inside my repo (and generating a change log of this repo) will fail because of the folder already existing.

`fatal: destination path 'my-folder-name' already exists and is not an empty directory.`

Might be useful to be able to override the target cloned directory with a parameter?

**Comment by ScottBrenner** [comment]
Addressed in https://github.com/ScottBrenner/generate-changelog-action/commit/9141a8160adcdaf769d16c22a35645ea0b60b7a2#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2, thanks for the report!
