### ISSUE TITLE
Error: no commits found

### ISSUE THREAD

**Issue by cawa-93** [ScottBrenner/generate-changelog-action#23]
At some point the commits stopped loading;
https://github.com/cawa-93/vite-electron-builder/runs/2122874127#step:6:7

If the error occurs, the workflow does not stop, so I did not immediately notice the problem.

I use generate-changelog-action to create notes for each release, automatically each time I push to main

There are currently no tags in the repository and commits have been loaded [from the initial](https://github.com/cawa-93/vite-electron-builder/runs/2103517393?check_suite_focus=true#step:6:7).

**Comment by ScottBrenner** [comment]
Does your repository have any tags?: https://github.com/cawa-93/vite-electron-builder/tags

https://github.com/ScottBrenner/generate-changelog-action/commit/a7403c00ca4253e9481f5fdc917c5c33fde5fd61 modified the Action to generate the changelog from previous tag to newest.

**Comment by cawa-93** [comment]
> Does your repository have any tags?: https://github.com/cawa-93/vite-electron-builder/tags

No. My workflow assumes that in that every tag = application release.

My repository is a template, so it doesn't have any releases or tags. There is only a draft release with a prepared history of changes.

I expected that all commits, starting with the initialization, would gather before the first tag. This will allow you to correctly generate a history of changes for the very first release.

**Comment by ScottBrenner** [comment]
Interesting, suggest using the previous release - https://github.com/marketplace/actions/generate-changelog-action?version=1.1.0 - as a workaround.

**Comment by cawa-93** [comment]
Hmmm ... What I do wrong?

https://github.com/cawa-93/vite-electron-builder/runs/2124585259#step:6:7

**Comment by ScottBrenner** [comment]
Ah sorry, https://github.com/marketplace/actions/generate-changelog-action?version=1.0.3 is the previous version to use.

**Comment by cawa-93** [comment]
Yes, the workaround worked. Thank you.
It would be great if the whole process fell apart when such errors occurred. This would allow you to notice the problem faster

**Comment by ScottBrenner** [comment]
https://github.com/ScottBrenner/generate-changelog-action/releases/tag/v1.2.0 added the ability to specify a tag range (or default to the previous), might help here.

**Comment by cawa-93** [comment]
Due to problems with the docker, I had to replace this action with [my own (though not perfect) solution](https://github.com/cawa-93/vite-electron-builder/blob/e6a234b514e9171e961a3341db54f4b9d8df1682/scripts/release-notes.js#L102-L106).
