### ISSUE TITLE
Action fail without errors

### ISSUE THREAD

**Issue by cawa-93** [ScottBrenner/generate-changelog-action#25]
Action run: https://github.com/cawa-93/vite-electron-builder/runs/2169683887

**Comment by cawa-93** [comment]
It seems that the problem does not depend on any specific code changes. It periodically [appears and disappears](https://github.com/cawa-93/vite-electron-builder/actions/workflows/CICD.yml?query=branch%3Amain).

**Comment by ScottBrenner** [comment]
Odd, could you try https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging ?

**Comment by cawa-93** [comment]
https://github.com/cawa-93/vite-electron-builder/runs/2210064902
[logs_767.zip](https://github.com/ScottBrenner/generate-changelog-action/files/6216497/logs_767.zip)

**Comment by ScottBrenner** [comment]
Thanks, see the Action printing
> `##[debug]Docker Action run completed with exit code 139`

(https://github.com/cawa-93/vite-electron-builder/runs/2210064902#step:7:31)

Googling around for "Docker exit code 139" makes it seem like an issue with [Alpine]( https://github.com/ScottBrenner/generate-changelog-action/blob/2d2b18776e43e11c90773867a6789350c80a56d3/Dockerfile#L1) and/or [Ubuntu](https://github.com/cawa-93/vite-electron-builder/blob/a5e1402f43459b1a6c9c4242e723813f830a4c61/.github/workflows/release.yml#L21)

**Comment by ScottBrenner** [comment]
Closing stale issue/cannot reproduce
